spring:
  application:
    name: pharma-connect-stock-service

logging:
  level:
    org:
      springframework.web: "debug"
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation=DEBUG:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql: TRACE
application:
  database:
    insert-dev-values: true
  jwt:
    secret: PxgfrbwwEfYXAf26-tZxhbXfez0ycDWhkPuOdmYGTqU
  client:
    authToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJQaGFybWFDb25uZWN0Iiwic3ViIjoic3RvY2siLCJyb2xlIjoiU0VSVklDRSIsInRva2VuVHlwZSI6IkFDQ0VTUyIsImlhdCI6MTcxNzQyMTUzNH0.NSJPVTdMSZb5FnYO90RkRmWLPzYrjQsb10CQSYcYFKs

# Actuator
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      # Zipkin
  tracing:
    sampling:
      probability: 1.0

# Eureka
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      stockBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state:
          seconds: 10
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: count_based
