# Use an official PostgreSQL image as the base
FROM postgres

# Set environment variables (optional)
ENV POSTGRES_DB your_database_name
ENV POSTGRES_USER your_username
ENV POSTGRES_PASSWORD your_password

# Copy SQL script to container
COPY init.sql /docker-entrypoint-initdb.d/

# Install PostGIS extension
RUN apt-get update && apt-get install -y postgis

# Expose the PostgreSQL port
EXPOSE 5432