name: pharma-connect-compose
version: "3.8"  # Updated version

services:
  postgres:
    container_name: pharma-db
    image: pharma-postgres
    networks:
      - postgres-net
    volumes:
      - pharma-db:/data/postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5432:5432"

  pgadmin:
    container_name: db-admin
    image: dpage/pgadmin4
    networks:
      - postgres-net
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-auth:/var/lib/pgadmin-auth
    ports:
      - "5050:80"

  registery:
    image: codebaker404/registery
    container_name: registery
    ports:
      - 8761:8761
    networks:
      - micro-services

  auth:
    image: codebaker404/ph-auth
    container_name: auth
    ports:
      - 8070:8070
    networks:
      - micro-services
      - postgres-net
    depends_on:
      - registery
      - config
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker


  stock:
    image: codebaker404/stock
    container_name: stock
    ports:
      - 8090:8090
    networks:
      - micro-services
      - postgres-net
    depends_on:
      - registery
      - config
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker


  config:
    image: codebaker404/config
    container_name: config
    ports:
      - 9000:9000
    networks:
      - micro-services
    depends_on:
      - registery
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker


  gateaway:
    image: codebaker404/ph-gateaway
    container_name: gateaway
    ports:
      - 8080:8080
    networks:
      - micro-services
    depends_on:
      - registery
    environment:
      - SPRING_PROFILES_ACTIVE=docker


  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - micro-services

networks:
  postgres-net:
    driver: bridge
  micro-services:
    driver: bridge

volumes:
  pharma-db:
  pgadmin-auth:
